{{- if .Values.cassandra.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thingsboard.fullname" . }}-cassandra-probe-config
  labels:
  {{- include "cassandra.labels" . | nindent 4 }}
data:
  probe: |
    if [[ $(nodetool status | grep $POD_IP) == *"UN"* ]]; then
       if [[ $DEBUG ]]; then
          echo "UN";
       fi
       exit 0;
    else
       if [[ $DEBUG ]]; then
          echo "Not Up";
       fi
       exit 1;
    fi
{{- end }}