{{- if .Values.cassandra.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "thingsboard.fullname" . }}-cassandra
  labels:
    {{- include "cassandra.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "thingsboard.fullname" . }}-cassandra
  replicas: 1
  selector:
    matchLabels:
      {{- include "cassandra.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cassandra.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: cassandra-probe-config
          configMap:
            name: {{ include "thingsboard.fullname" . }}-cassandra-probe-config
            items:
              - key: probe
                path: ready-probe.sh
                mode: 0777
      terminationGracePeriodSeconds: 1800
      containers:
        - name: cassandra
          image: {{ .Values.cassandra.image.repository }}:{{ .Values.cassandra.image.tag }}
          imagePullPolicy: {{ .Values.cassandra.image.pullPolicy }}
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cql
              protocol: TCP
            - containerPort: 9160
              name: thrift
          resources:
            {{- toYaml .Values.cassandra.resources | nindent 12 }}
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - nodetool drain
          env:
            - name: CASSANDRA_SEEDS
              value: "{{ include "thingsboard.fullname" . }}-cassandra-0.{{ include "thingsboard.fullname" . }}-cassandra.{{ .Release.Namespace }}.svc.cluster.local"
            - name: MAX_HEAP_SIZE
              value: 1024M
            - name: HEAP_NEWSIZE
              value: 256M
            - name: CASSANDRA_CLUSTER_NAME
              value: "Thingsboard Cluster"
            - name: CASSANDRA_DC
              value: "datacenter1"
            - name: CASSANDRA_RACK
              value: "Rack-Thingsboard-Cluster"
            - name: CASSANDRA_AUTO_BOOTSTRAP
              value: "false"
            - name: CASSANDRA_ENDPOINT_SNITCH
              value: GossipingPropertyFileSnitch
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /probe/ready-probe.sh
            initialDelaySeconds: 60
            timeoutSeconds: 5
          volumeMounts:
            - name: cassandra-probe-config
              mountPath: /probe
            - name: cassandra-data
              mountPath: /var/lib/cassandra
  volumeClaimTemplates:
    - metadata:
        name: cassandra-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
{{- end }}