{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thingsboard.fullname" . }}-postgres-db-config
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
data:
  DATABASE_TS_TYPE: sql
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{ include "thingsboard.fullname" . }}-postgres:{{.Values.postgres.service.port }}/thingsboard
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.dbPassword }}
{{- end }}