#
# Copyright © 2016-2022 The Thingsboard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '3.0'

services:
  # Redis sentinel
  redis-master:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
    volumes:
      - ./tb-node/redis-sentinel/master:/bitnami/redis/data
    ports:
      - '127.0.0.1:6379:6379'
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_PORT=7000
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
    ports:
      - '127.0.0.1:7000:7000'
    volumes:
      - ./tb-node/redis-sentinel/slave:/bitnami/redis/data
    depends_on:
      - redis-master
  redis-sentinel:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis-master
      - redis-slave
    volumes:
      - ./tb-node/redis-sentinel/sentinel:/bitnami/redis/data
    ports:
      - '127.0.0.1:26379:26379'

  # ThingsBoard setup to use redis-standalone
  tb-core1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-core2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-rule-engine1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-rule-engine2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-mqtt-transport1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-mqtt-transport2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-http-transport1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-http-transport2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-coap-transport:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-lwm2m-transport:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-snmp-transport:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-vc-executor1:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
  tb-vc-executor2:
    env_file:
      - cache-redis-sentinel.env
    depends_on:
      - redis-sentinel
