mqtt:
  url: "${MQTT_URL:tcp://localhost:1883}"
  qos: "${MQTT_QOS:1}"
  timeout: "${MQTT_TIMEOUT:5000}"
  monitoring_rate: "${MQTT_MONITORING_RATE:10000}"
  test_device:
    access_token: "${MQTT_TEST_DEVICE_ACCESS_TOKEN:qMlayxUWDAFsXmiVcUGr}"
    id: "${MQTT_TEST_DEVICE_ID:db96cbe0-1b96-11ec-9bbf-7165a6bd0cd0}"

http:
  url: "${HTTP_URL:tcp://localhost:1883}"
  qos: "${HTTP_QOS:1}"
  timeout: "${HTTP_TIMEOUT:5000}"
  monitoring_rate: "${HTTP_MONITORING_RATE:10000}"
  test_device:
    access_token: "${HTTP_TEST_DEVICE_ACCESS_TOKEN:ikoLNfBDlNE3zO6wTekL}"
    id: "${HTTP_TEST_DEVICE_ID:dfe0d1a0-1b96-11ec-9bbf-7165a6bd0cd0}"

lwm2m:
  url: "${HTTP_URL:tcp://localhost:1883}"
  qos: "${HTTP_QOS:1}"
  timeout: "${HTTP_TIMEOUT:5000}"
  monitoring_rate: "${HTTP_MONITORING_RATE:10000}"
  test_device:
    access_token: "${HTTP_TEST_DEVICE_ACCESS_TOKEN:PJP6ZPVxK881XeK4QDZe}"

coap:
  url: "${HTTP_URL:coap://localhost}"
  qos: "${HTTP_QOS:1}"
  timeout: "${HTTP_TIMEOUT:5000}"
  monitoring_rate: "${HTTP_MONITORING_RATE:10000}"
  test_device:
    access_token: "${HTTP_TEST_DEVICE_ACCESS_TOKEN:MtyXwpFyKKcNJhwVMi09}"
    id: "${WEBSOCKET_DEVICE_ID:d6089640-1baa-11ec-8009-5572699cb133}"

snmp:
  url: "${HTTP_URL:tcp://localhost:1883}"
  qos: "${HTTP_QOS:1}"
  timeout: "${HTTP_TIMEOUT:5000}"
  monitoring_rate: "${HTTP_MONITORING_RATE:10000}"
  test_device:
    access_token: "${HTTP_TEST_DEVICE_ACCESS_TOKEN:MtyXwpFyKKcNJhwVMi09}"
    id: "${WEBSOCKET_DEVICE_ID:d6089640-1baa-11ec-8009-5572699cb133}"

websocket:
  wait_time: "${WEBSOCKET_WAIT_TIME:10000}"
  monitoring_tenant_username: "${WEBSOCKET_MONITORING_TENANT_USERNAME:monitoring@gmail.com}"
  monitoring_tenant_password: "${WEBSOCKET_MONITORING_TENANT_PASSWORD:tenant}"

#TODO refactor env variables
