apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thingsboard.fullname" . }}-node-db-config
  labels:
  {{- include "thingsboard.labels" . | nindent 4 }}
data:
  SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
  SPRING_DRIVER_CLASS_NAME: org.postgresql.Driver
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{ include "thingsboard.fullname" . }}-postgres:{{.Values.postgres.service.port }}/thingsboard
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.dbPassword }}
  {{- if .Values.cassandra.enabled }}
  DATABASE_TS_TYPE: cassandra
  CASSANDRA_URL: cassandra:9042
  CASSANDRA_SOCKET_READ_TIMEOUT: "60000"
  {{- else }}
  DATABASE_TS_TYPE: sql
  {{- end }}