apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thingsboard.fullname" . }}-node-db-secret
  labels:
    {{- include "thingsboard.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if and .Values.postgres.enabled (not .Values.postgres.existingSecretName) }}
  # if local postgres enabled, and not provided existing secrets
  SPRING_DATASOURCE_URL: jdbc:postgresql://{{ include "thingsboard.fullname" . }}-postgres:{{.Values.postgres.service.port }}/thingsboard
  SPRING_DATASOURCE_USERNAME: {{ .Values.postgres.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.postgres.password }}
  {{- else if and (not .Values.postgres.enabled ) (not .Values.externalPostgres.existingSecretName) }}
  # if external postgres configured, and not provided existing secrets
  SPRING_DATASOURCE_URL: {{ .Values.externalPostgres.postgresUrl }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.externalPostgres.username }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.externalPostgres.password }}
  {{- end }}