name: Tesenso CI/CD Pipeline

on:
  push:
    branches: [ "read-pom" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build tesenso middleware core
        run: mvn clean package -DskipTests

#      - name: Get artifact ID
#        run: |
#          sudo apt-get install xmlstarlet
#          ARTIFACT_ID=$(xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:artifactId" pom.xml)
#          VERSION=$(xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:version" pom.xml)
#          VAR3="${ARTIFACT_ID}-${VERSION}.deb"
#          echo "$VAR3"

      - name: Get artifact id & rename deb file name
        run: |
          sudo apt-get install xmlstarlet
          ARTIFACT_ID=$(xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:artifactId" pom.xml)
          VERSION=$(xmlstarlet sel -N x=http://maven.apache.org/POM/4.0.0 -t -v "/x:project/x:version" pom.xml)
          VAR3="${ARTIFACT_ID}-${VERSION}.deb"
          echo "$VAR3"
          cd application/target/
          mv thingsboard.deb "$VAR3"
          ls
          pwd
#
      - name: Transfer to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          source: '*.deb'
          target: '/opt/tesenso'
#
#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#    steps:
#      - name: Deploy to the server
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SERVER_IP }}
#          username: ${{ secrets.SERVER_USERNAME }}
#          password: ${{ secrets.SERVER_PASSWORD }}
#          port: ${{ secrets.SERVER_PORT }}
#          script: |
#            sudo chmod -R 777 /opt/tesenso/application/target/*
#            sudo dpkg -i /opt/tesenso/application/target/thingsboard.deb
