name: Java App Build and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build and Package
        run: mvn clean package -DskipTests

      - name: Copy Artifact via SCP
        uses: appleboy/scp-action@master
        with:
          host: 20.14.100.97
          username: kawsarahmd
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: /home/runner/work/thingsboard/thingsboard/application/target/thingsboard.deb
          target: /opt/tesenso
