name: Java App Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build and Package
        run: mvn clean package

      - name: Copy Artifact via SCP
        uses: appleboy/scp-action@master
        with:
          host: <remote-server-hostname>
          username: <remote-server-username>
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: /home/runner/work/thingsboard/thingsboard/application/target/thingsboard.deb
          target: /opt/tesenso
